services:
  db:
    image: postgres:16
    container_name: lexora_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: lexora_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lexora.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis:7-alpine
    container_name: lexora_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.build
  #   container_name: lexora_backend
  #   ports:
  #     - "127.0.0.1:4000:4000"
  #   volumes:
  #     - ./keys:/app/keys:ro
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=4000
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     - GOOGLE_VERTEX_AI_JSON_PATH=./keys/lexora-vertex-ai.json
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   env_file:
  #     - .env

volumes:
  pgdata:
  pgadmin:
  redis_data:
